name: "Transmission"
homeassistant: "2023.11.3"
description: "Transmission is a popular, fast, open-sourced BitTorrent client with an easy to use web UI."
url: "https://github.com/maorcc/hassio-addon-transmission/tree/main/transmission"
version: "1.2.1"
slug: "transmission"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_entry: transmission/web/
ingress_port: 9091
map:
  - addon_config:rw
  - media:rw
  - share:rw
ports:
  9091/tcp: null
  51413/tcp: 51413
  51413/udp: 51413
image: "ghcr.io/maorcc/{arch}-hassio-addon-transmission"
